---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-app-one-pipeline-run-
spec:
  params:
    - name: source-repo
      value:https://github.com/WandeT/express-sample-app.git
    - name: image-repo
      value: quay.io/yewande_toriola_ibm / express-sample-app
    - name: app-name
      value: express-sample-app
  serviceAccountName: build-bot
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi